name: Deploy Alvegest via SFTP
 
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: 🚚 Get latest code
        uses: actions/checkout@v3

      - name: 🚀 SFTP Deploy
        uses: wlixcc/SFTP-Deploy-Action@v1.2.4
        with:
          username: ${{ secrets.SFTP_USERNAME }}
          server: ${{ secrets.SFTP_SERVER }}
          password: ${{ secrets.SFTP_PASSWORD }}
          port: 22
          local_path: './*' # Carica tutto il contenuto della repo
          remote_path: '/web/alvegest' # Il percorso esatto sul tuo NAS
          sftp_args: '-o ConnectTimeout=5'
